committee_size: 5
committee_cooldown: 3
rep_exponent: 1.0

detection:
  name: flame_v2
  params:
    min_points: 4
    min_cluster_frac: 0.2
    dbscan_eps: 0.3
    detect_score_thresh: 0.05

aggregation:
  # name: fedavg
  name: flame_agg
  params:
    percentile: 0.8
    epsilon: 8.0
    delta: 1e-5
    use_clipping: True
    use_noise: False

selection:
  name: stratified_softmax
  params:
    committee_size: 3
    rep_exponent: 1.0
    cooldown: 3
    num_strata: 3

settlement:
  name: plans_engine
  params:
    warmup_rounds: 1

reward:
  name: default
  params:
    base_reward: 100.0
    hist_decay: 0.9
    stake_weight: 0.4

penalty:
  name: default
  params:
    stake_penalty_factor: 0.02
    rep_penalty_factor: 0.5

reputation:
  name: default
  params:
    X_c: 10.0
    X_s: 5.0
    rep_cap_early: 300.0
    rep_cap_late: 500.0
    rep_cap_round: 50
    contrib_base: 0.0
    contrib_thre: 1.0
