# configs/exp_flame.yaml
detection:
  name: flame
aggregation:
  name: flame_agg       # FLAME aggregation
selection:
  name: none
reward:
  name: none
penalty:
  name: none
reputation:
  name: none
settlement:
  name: none
