# configs/exp_fedavg.yaml
aggregation:
  name: fedavg         # FedAvg implementation
selection:
  name: none         # include every client, no committee
reward:
  name: none            # disable reward/penalty/reputation modules
penalty:
  name: none
reputation:
  name: none
settlement:
  name: none
